##############################
# JIRA CONFIGURATION
##############################

jira.base.url=https://nitishgaurav95.atlassian.net/
jira.user=nitishgaurav95@gmail.com
jira.token=ATATT3xFfGF0zyaBOQmHXr92xBrZYCG8uQjod6vQNeUkrR_qDiVK_Z2S05IS3vemh9Y8licddxv5WJeacz4fRpc9HHnl4wiwoP_uYZdGnYjmKz17f0ZNHbOCpyS2MIz58feblmS5PSm-3T0zUxVAdXB7-YxYcv8pDbRj07e-sZkh40SRMa8n_7w=C55B7F73
jira.issue=TES-7

##############################
# ENVIRONMENT CONFIG
##############################

env=qa
browser=chrome
timeout=20

##############################
# OPTIONAL OTHER API CONFIG
##############################

api.base.url=https://api.test.com
api.username=testuser
api.password=testpass